spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: password

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql:true
        use_sql_comments=true
    defer-datasource-initialization: true

  sql:
    init:
      continue-on-error: true
      mode: always
      data-locations: classpath:products.sql, classpath:init-data.sql

  session:
    jdbc:
      initialize-schema: always

  docker:
    compose:
      enabled: false